/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SpecRouteImport } from './routes/spec'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as FeaturesImportRouteImport } from './routes/features.import'
import { Route as FeaturesFeatureIdRouteImport } from './routes/features.$featureId'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecRoute = SpecRouteImport.update({
  id: '/spec',
  path: '/spec',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesImportRoute = FeaturesImportRouteImport.update({
  id: '/features/import',
  path: '/features/import',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesFeatureIdRoute = FeaturesFeatureIdRouteImport.update({
  id: '/features/$featureId',
  path: '/features/$featureId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agent': typeof AgentRoute
  '/dashboard': typeof DashboardRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/spec': typeof SpecRoute
  '/terminal': typeof TerminalRoute
  '/features/$featureId': typeof FeaturesFeatureIdRoute
  '/features/import': typeof FeaturesImportRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agent': typeof AgentRoute
  '/dashboard': typeof DashboardRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/spec': typeof SpecRoute
  '/terminal': typeof TerminalRoute
  '/features/$featureId': typeof FeaturesFeatureIdRoute
  '/features/import': typeof FeaturesImportRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agent': typeof AgentRoute
  '/dashboard': typeof DashboardRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/spec': typeof SpecRoute
  '/terminal': typeof TerminalRoute
  '/features/$featureId': typeof FeaturesFeatureIdRoute
  '/features/import': typeof FeaturesImportRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/agent'
    | '/dashboard'
    | '/kanban'
    | '/login'
    | '/settings'
    | '/spec'
    | '/terminal'
    | '/features/$featureId'
    | '/features/import'
    | '/projects/$projectId'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/agent'
    | '/dashboard'
    | '/kanban'
    | '/login'
    | '/settings'
    | '/spec'
    | '/terminal'
    | '/features/$featureId'
    | '/features/import'
    | '/projects/$projectId'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/agent'
    | '/dashboard'
    | '/kanban'
    | '/login'
    | '/settings'
    | '/spec'
    | '/terminal'
    | '/features/$featureId'
    | '/features/import'
    | '/projects/$projectId'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AgentRoute: typeof AgentRoute
  DashboardRoute: typeof DashboardRoute
  KanbanRoute: typeof KanbanRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SpecRoute: typeof SpecRoute
  TerminalRoute: typeof TerminalRoute
  FeaturesFeatureIdRoute: typeof FeaturesFeatureIdRoute
  FeaturesImportRoute: typeof FeaturesImportRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec': {
      id: '/spec'
      path: '/spec'
      fullPath: '/spec'
      preLoaderRoute: typeof SpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/import': {
      id: '/features/import'
      path: '/features/import'
      fullPath: '/features/import'
      preLoaderRoute: typeof FeaturesImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$featureId': {
      id: '/features/$featureId'
      path: '/features/$featureId'
      fullPath: '/features/$featureId'
      preLoaderRoute: typeof FeaturesFeatureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AgentRoute: AgentRoute,
  DashboardRoute: DashboardRoute,
  KanbanRoute: KanbanRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SpecRoute: SpecRoute,
  TerminalRoute: TerminalRoute,
  FeaturesFeatureIdRoute: FeaturesFeatureIdRoute,
  FeaturesImportRoute: FeaturesImportRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
